name: merging_builder
description: MergingBuilder reads several input files and writes merged output
  to one file. StandaloneBuilder enables output to a custom folder with custom
  output file name.
version: 0.2.7
repository: https://github.com/nicodanke/merging_builder
publish_to: https://pub-server-staging.fu.do
homepage: https://github.com/simphotonics/merging_builder

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  build_runner: ^2.4.6
  dart_style: ^2.3.4
  directed_graph: ^0.4.0
  exception_templates: ^0.3.0
  file: ^7.0.0
  glob: ^2.1.1
  lazy_memo: ^0.2.2
  meta: ^1.9.1
  path: ^1.8.3
  quote_buffer: ^0.2.3
  source_gen: ^1.2.6
dependency_overrides: null
dev_dependencies:
  build_test: ^2.1.5
  crypto: ^3.0.2
  lints: ^3.0.0
  test: ^1.22.1
